"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

export type MfaStatus = { enabled: boolean; enrollment_required: boolean; recovery_codes_remaining: number };

type Setup = { secret: string; qr_code: string };

export function MfaSettings({ enrollment = false, onStatusChange }: { enrollment?: boolean; onStatusChange?: (status: MfaStatus) => void }) {
  const router = useRouter();
  const [status, setStatus] = useState<MfaStatus | null>(null);
  const [setup, setSetup] = useState<Setup | null>(null);
  const [codes, setCodes] = useState<string[]>([]);
  const [password, setPassword] = useState("");
  const [code, setCode] = useState("");
  const [confirmCode, setConfirmCode] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);

  async function load() { const result = await api<MfaStatus>("/auth/mfa/status"); setStatus(result); onStatusChange?.(result); }
  useEffect(() => { load().catch(err => setError(err.message)); }, []);
  async function run(action: () => Promise<void>) {
    setError(""); setBusy(true);
    try { await action(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível concluir."); }
    finally { setBusy(false); }
  }
  function start(event: FormEvent) {
    event.preventDefault();
    run(async () => {
      const result = await api<Setup>("/auth/mfa/setup", { method: "POST", body: JSON.stringify({ password, code }) });
      setSetup(result); setPassword(""); setCode(""); setCodes([]);
    });
  }
  function confirm(event: FormEvent) {
    event.preventDefault();
    run(async () => {
      const result = await api<{ recovery_codes: string[] }>("/auth/mfa/confirm", { method: "POST", body: JSON.stringify({ code: confirmCode }) });
      setSetup(null); setConfirmCode(""); setCodes(result.recovery_codes); setSaved(false); await load();
    });
  }

  return <section className="security-card mfa-card">
    <h2>Autenticação em duas etapas</h2>
    <p>Use Google Authenticator, Microsoft Authenticator ou outro aplicativo compatível com TOTP.</p>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!status && <p>Carregando configuração…</p>}
    {status && <p><strong>{status.enabled ? "MFA ativado" : "MFA ainda não ativado"}</strong>{status.enabled && ` · ${status.recovery_codes_remaining} códigos de recuperação disponíveis.`}</p>}
    {enrollment && status?.enabled && !setup && codes.length === 0 && <button className="button" onClick={() => router.replace("/")}>Acessar plataforma</button>}
    {status?.enrollment_required && <p>Cadastre seu autenticador para acessar a plataforma.</p>}
    {codes.length > 0 ? <div>
      <h3>Guarde seus códigos de recuperação</h3>
      <p>Estes códigos aparecem somente agora. Guarde-os em um gerenciador de senhas. Cada um substitui o código do autenticador uma única vez.</p>
      <pre className="recovery-codes" tabIndex={0}>{codes.join("\n")}</pre>
      <label className="mfa-saved"><input type="checkbox" checked={saved} onChange={e => setSaved(e.target.checked)} /> Guardei os códigos em um local seguro</label>
      <button className="button primary" disabled={!saved} onClick={() => { setCodes([]); if (enrollment) router.replace("/"); }}>Concluir</button>
    </div> : setup ? <form onSubmit={confirm}>
      <p>Escaneie o QR code no autenticador ou informe a chave manualmente. A configuração expira em dez minutos.</p>
      {/* Generated by our API; never sent to a QR service or an image optimizer. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img className="mfa-qr" src={setup.qr_code} alt="QR code para cadastrar seu autenticador DeepOps" width={240} height={240} />
      <label>Chave de configuração<input readOnly value={setup.secret} autoComplete="off" spellCheck={false} /></label>
      <p>Tipo: baseado em tempo (TOTP) · 6 dígitos · 30 segundos. Não compartilhe a chave.</p>
      <label>Código do novo autenticador<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={confirmCode} onChange={e => setConfirmCode(e.target.value)} required /></label>
      <div className="security-actions"><button className="button primary" disabled={busy}>Confirmar ativação</button><button className="button" type="button" disabled={busy} onClick={() => { setSetup(null); setConfirmCode(""); }}>Voltar</button></div>
    </form> : status && <form onSubmit={start}>
      {status.enabled && <p>Para trocar o autenticador ou gerar novos códigos de recuperação, confirme sua senha e um segundo fator. A troca encerra as outras sessões e invalida os códigos anteriores.</p>}
      <label>Sua senha<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label>
      {status.enabled && <label>Código atual ou de recuperação<input autoComplete="one-time-code" maxLength={64} value={code} onChange={e => setCode(e.target.value)} required /></label>}
      <div className="security-actions"><button className="button primary" disabled={busy}>{status.enabled ? "Trocar autenticador" : "Configurar autenticador"}</button>
      {status.enabled && <button className="button" type="button" disabled={busy || !password || !code} onClick={() => run(async () => {
        const result = await api<{ recovery_codes: string[] }>("/auth/mfa/recovery-codes", { method: "POST", body: JSON.stringify({ password, code }) });
        setPassword(""); setCode(""); setCodes(result.recovery_codes); setSaved(false); await load();
      })}>Gerar novos códigos</button>}</div>
    </form>}
  </section>;
}
